version: "3.8"

services:
  api:
    build: .
    command: npm run start:dev
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src:cached      
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
    # env_file:
    #   - .env

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    logging:
        driver: none
