version: "3.8"

services:
  api:
    build: .
    command: npm run start:dev
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./bin:/usr/src/app/bin:cached
    environment:
      - PORT=5000
      - LOG_LEVEL=debug
      - MODE=API
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - REDIS_URL=redis://redis:6379
      - API_HOST=http://localhost:5000
      - APP_HOST=http://localhost:3000
    env_file:
      - .env

  sockets:
    build: .
    command: npm run start:dev
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./bin:/usr/src/app/bin:cached
    environment:
      - PORT=5001
      - LOG_LEVEL=debug
      - MODE=SOCKETS
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - REDIS_URL=redis://redis:6379
      - API_HOST=http://localhost:5000
      - APP_HOST=http://localhost:3000
    env_file:
      - .env

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    logging:
        driver: none

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    logging:
        driver: none
