version: "3.8"

services:
  sockets:
    build: .
    command: npm run start:dev
    depends_on:
      - redis
    ports:
      - "5001:5001"
    volumes:
      - ./src:/usr/src/app/src:cached
      - ../platform-api:/usr/src/platform-api:cached
    environment:
      - PORT=5001
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - REDIS_URL=redis://redis:6379
      - API_HOST=http://localhost:5000
      - LOG_LEVEL=debug

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    logging:
        driver: none

networks:
  default:
    external:
      name: homefield-network
